[project]
name = "questrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepagents>=0.5.3",
    "dotenv>=0.9.9",
    "langchain",
    "langchain-community>=0.4.1",
    "langchain-openai",
    "pypdf>=6.10.2",
    "pytest>=9.0.3",
]

[tool.ruff.lint]
# 选择要检查的规则
select = ["E", "W", "F", "I", "UP"]
# 忽略特定的规则
ignore = ["E501", "F401"]


